global_defaults:
  cluster_port: "8201"
  cluster_name: "vault_cluster"
  api_port: "8200"
  docker_image_name: "myopenbao"

#openbao_instances:
#  - name: vault_node_1
#    host: myhost-4.dev.local
#    cluster_addr_url: "http://myhost-4.dev.local:{{ cluster_port }}"
#    api_addr_url: "http://myhost-4.dev.local:{{ api_port }}"
#    cluster_port: "8201"
#    api_port: "8200"
#  - name: vault_node_2
#    host: myhost-5.dev.local
#    cluster_addr_url: "http://myhost-5.dev.local:{{ cluster_port }}"
#    api_addr_url: "http://myhost-5.dev.local:{{ api_port }}"
#    cluster_port: "8201"
#    api_port: "8200"
#  - name: vault_node_3
#    host: myhost-6.dev.local
#    cluster_addr_url: "http://myhost-6.dev.local:{{ cluster_port }}"
#    api_addr_url: "http://myhost-6.dev.local:{{ api_port }}"
#    cluster_port: "8201"
#    api_port: "8200"
#
