---
- name: Create Dockerfile
  template:
    src: Dockerfile.j2
    dest: ./Dockerfile
    mode: 0644

- name: Docker build image
  become: true
  community.docker.docker_image:
    name: "{{ docker_image_name }}"
#    name: "{{ hostvars['openbao_instances'][0]['docker_image_name'] }}"
    source: build
#    tag: latest
    build:
      path: ./

- name: Create openbao.hcl config file
  template:
    src: openbao.hcl.j2
    dest: ./openbao.hcl
    mode: 0644
#  notify:
#    - Run container

- name: Remove Container
  community.docker.docker_container:
    name: "{{ openbao_container_name }}"
    force_kill: true
    state: absent
    keep_volumes: false

- name: Run container
  community.docker.docker_container:
    name: "{{ openbao_container_name }}"
    image: "{{ docker_image_name }}"
    state: started
    detach: yes
    memory_swappiness: 0
    ports:
      - "{{ cluster_port }}:{{ cluster_port }}"
      - "{{ api_port }}:{{ api_port }}"
    env:
      BAO_DEV_ROOT_TOKEN_ID: "foobar"
      VAULT_CLUSTER_ADDR: "http://{{ host }}:{{ cluster_port }}"
      VAULT_ADDR: "http://{{ host }}:{{ api_port }}"
      VAULT_SKIP_VERIFY: "true"
      VAULT_TOKEN: "s.rxOcFhVFcPNMiwwwtSeMMtgT"
    volumes:
      - "/root/openbao.hcl:{{ raft_dir }}/data/openbao.hcl"
    capabilities:
      - IPC_LOCK
    command: server -config="{{ raft_dir }}/data/openbao.hcl"
